//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tBookData
    {
        public int BOOK_ID { get; set; }
        public string BOOK_NAME { get; set; }
        public string BOOK_CLASS_ID { get; set; }
        public string BOOK_AUTHOR { get; set; }
        public Nullable<System.DateTime> BOOK_BOUGHT_DATE { get; set; }
        public string BOOK_PUBLISHER { get; set; }
        public string BOOK_NOTE { get; set; }
        public string BOOK_STATUS { get; set; }
        public string BOOK_KEEPER { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_USER { get; set; }
        public Nullable<System.DateTime> MODIFY_DATE { get; set; }
        public string MODIFY_USER { get; set; }
    }
}
